import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createClient } from "@/lib/supabase";
import { signOut } from "./actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Nav bar: shows different links when logged in (gated UI) */}
        <nav style={{ display: "flex", gap: "1rem", padding: "1rem 2rem", borderBottom: "1px solid #ccc" }}>
          <Link href="/">Home</Link>
          {user ? (
            <>
              <Link href="/members">Members</Link>
              <Link href="/profile">Profile</Link>
              <form action={signOut}><button>Log out</button></form>
            </>
          ) : (
            <Link href="/login">Log in</Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
